set -g @tmux-gruvbox 'dark'

# enable transparent statusbar (optional)
set -g @tmux-gruvbox-statusbar-alpha 'true'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
